import type { DefinePageConfig } from "vite-plugin-uni-inject";

// Auto-generated by vite-plugin-uni-inject. Do not edit.

/**
 * 提取路径
 */
export type ExtractPath<
  T extends string,
  Prefix extends string,
> = T extends `${Prefix}${infer P}` ? P : never;

/**
 * 路由路径
 */
export type RoutePath =
  | "/modules/example/pages/test"
  | "/pages/index/index"
  | "/sub-packages/tutorial/views/index";

declare global {
  /**
   * Vue `<script setup>` 宏定义 uniapp 页面级配置。
   */
  function definePage(config: DefinePageConfig): void;
}
