import type { AutoPagesPluginOptions, UniPagesJson, UniPage } from "./types";
import fs from "fs";
import path from "path";

// 路径统一转换为 posix 风格
function toPosixPath(value: string) {
  return value.replace(/\\/g, "/");
}

// 目录统一转换为 posix 风格
function normalizeDir(value: string) {
  return toPosixPath(value).replace(/^\/+|\/+$/g, "");
}

// 递归收集指定目录下的全部文件
function walkFiles(dirPath: string, filePaths: string[] = []) {
  if (!fs.existsSync(dirPath)) {
    return filePaths;
  }
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      walkFiles(fullPath, filePaths);
      continue;
    }
    filePaths.push(fullPath);
  }
  return filePaths;
}

// 收集指定目录下的文件路由排序
function collectFileRoutes(srcRoot: string, routeDirs: string[]) {
  const routeSet = new Set<string>();
  routeDirs.forEach((dir) => {
    const absDir = path.resolve(srcRoot, dir);
    const files = walkFiles(absDir);
    files.forEach((filePath) => {
      if (!filePath.endsWith(".vue")) {
        return;
      }
      const rel = path.relative(srcRoot, filePath);
      const noExt = rel.slice(0, -4);
      routeSet.add(toPosixPath(noExt));
    });
  });
  return Array.from(routeSet).sort();
}

// 获取需要扫描的目录列表
function getScanDirs(dir: string, subPackages: string[]) {
  const dirSet = new Set<string>();
  const normalizedMainDir = normalizeDir(dir);
  if (normalizedMainDir) {
    dirSet.add(normalizedMainDir);
  }
  subPackages.forEach((subRoot) => {
    const normalizedSubRoot = normalizeDir(subRoot);
    if (!normalizedSubRoot) {
      return;
    }
    if (normalizedMainDir) {
      dirSet.add(`${normalizedSubRoot}/${normalizedMainDir}`);
      return;
    }
    dirSet.add(normalizedSubRoot);
  });
  return Array.from(dirSet);
}

// 读取 pages.json 文件
function readPagesJson(pagesJsonPath: string) {
  if (!fs.existsSync(pagesJsonPath)) {
    return null;
  }
  const content = fs.readFileSync(pagesJsonPath, "utf-8");
  return JSON.parse(content) as UniPagesJson;
}

// 合并页面配置，保留原有属性
function mergePages(routes: string[], existingPages: UniPage[]) {
  const existingMap = new Map(existingPages.map((p) => [p.path, p]));
  return routes.map((route) => {
    return existingMap.get(route) ?? { path: route };
  });
}

// 判断页面配置是否发生变化
function hasPagesJsonChanged(current: UniPagesJson, next: UniPagesJson) {
  return (
    JSON.stringify({
      pages: next.pages,
      subPackages: next.subPackages ?? [],
    }) !==
    JSON.stringify({
      pages: current.pages ?? [],
      subPackages: current.subPackages ?? [],
    })
  );
}

// 获取基于文件路由的 pages.json 配置
function getPagesByFileRoute(
  routes: string[],
  pagesJson: UniPagesJson,
  subPackageRoots: string[],
) {
  const originPages = pagesJson.pages ?? [];
  const originSubPackages = pagesJson.subPackages ?? [];

  // 将路由按主包和分包进行分类
  const mainRoutes: string[] = [];
  const subRouteMap = new Map<string, string[]>();
  const normalizedSubRoots = subPackageRoots.map(normalizeDir);
  for (const route of routes) {
    const matchedRoot = normalizedSubRoots.find((root) => {
      return route.startsWith(root + "/");
    });
    if (matchedRoot) {
      const subPath = route.slice(matchedRoot.length + 1);
      const list = subRouteMap.get(matchedRoot) ?? [];
      list.push(subPath);
      subRouteMap.set(matchedRoot, list);
    } else {
      mainRoutes.push(route);
    }
  }

  // 保持首页固定
  const homePage = originPages[0]?.path;
  if (mainRoutes.includes(homePage)) {
    const idx = mainRoutes.indexOf(homePage);
    mainRoutes.splice(idx, 1);
    mainRoutes.unshift(homePage);
  }

  // 合并页面配置
  const pages = mergePages(mainRoutes, originPages);
  const subPackages = normalizedSubRoots.map((root) => {
    const subRoutes = subRouteMap.get(root) ?? [];
    const existing = originSubPackages.find((s) => {
      return normalizeDir(s.root) === root;
    });
    return {
      root,
      pages: mergePages(subRoutes, existing?.pages ?? []),
    };
  });

  const merged = {
    ...pagesJson,
    pages,
    subPackages,
  };

  return {
    merged,
    changed: hasPagesJsonChanged(pagesJson, merged),
  };
}

// 解析 dts 文件路径
function resolveDtsFilePath(srcRoot: string, dts: string) {
  return path.isAbsolute(dts) ? dts : path.resolve(srcRoot, dts);
}

// 生成路由类型声明文件
function buildRouteDts(routes: string[]) {
  const routeUnion = routes.map((route) => `  | "/${route}"`).join("\n");
  return [
    "// Auto-generated by vite-plugin-uni-inject. Do not edit.",
    "",
    "/** 提取路径 */",
    "export type ExtractPath<T extends string, Prefix extends string> = T extends `${Prefix}${infer P}` ? P : never;",
    "",
    "/** 路由路径 */",
    "export type RoutePath =",
    routeUnion + ";",
    "",
  ].join("\n");
}

/**
 * 自动补全 pages.json 插件
 */
export default function uniAutoPages(opts?: AutoPagesPluginOptions) {
  const {
    dir = "pages",
    subPackages = [],
    dts = "uni-pages.d.ts",
  } = opts || {};

  return {
    name: "vite-plugin-uni-auto-pages",
    enforce: "pre" as const,

    // 插件初始化
    configResolved(config: { root: string }) {
      const srcRoot = path.resolve(config.root, "src");

      // 读取 pages.json 文件
      const pagesJsonPath = path.join(srcRoot, "pages.json");
      const pagesJson = readPagesJson(pagesJsonPath);
      if (!pagesJson) {
        return;
      }

      const scanDirs = getScanDirs(dir, subPackages);
      const routes = collectFileRoutes(srcRoot, scanDirs);

      // 获取基于文件路由的 pages.json 配置
      const { merged, changed } = getPagesByFileRoute(
        routes,
        pagesJson,
        subPackages,
      );

      // 写入基于文件路由的 pages.json 配置
      if (changed) {
        fs.writeFileSync(pagesJsonPath, JSON.stringify(merged, null, 2) + "\n");
      }

      // 生成类型声明文件，提供页面路由的类型支持
      if (dts) {
        const dtsFilePath = resolveDtsFilePath(srcRoot, dts);
        const dtsContent = buildRouteDts(routes);
        fs.writeFileSync(dtsFilePath, dtsContent);
      }
    },
  };
}
